# Generated by Django 3.2.5 on 2022-04-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vessel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missile',
            name='default_num',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='missile',
            name='type',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
