# Generated by Django 3.2.5 on 2022-04-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vessel', '0002_auto_20220419_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='missile',
            name='belongs_to',
            field=models.CharField(choices=[('e', 'Enemy'), ('a', 'Ally'), ('b', 'Both')], default='b', max_length=1),
        ),
    ]
