# Generated by Django 3.2.5 on 2022-04-19 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vessel', '0004_vessil'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vessil',
            new_name='Vessel',
        ),
    ]
