# Generated by Django 3.2.5 on 2022-06-01 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vessel', '0006_auto_20220419_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='default_fires',
        ),
        migrations.AddField(
            model_name='vessel',
            name='default_fires',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Vessel.missile'),
        ),
    ]
