# Generated by Django 3.2.5 on 2022-06-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vessel', '0008_auto_20220601_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vessel',
            old_name='default_fire1',
            new_name='fire1',
        ),
        migrations.RenameField(
            model_name='vessel',
            old_name='default_fire2',
            new_name='fire2',
        ),
    ]
