# Generated by Django 3.2.5 on 2022-06-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vessel', '0009_auto_20220601_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missile',
            name='belongs_to',
            field=models.CharField(choices=[('e', '敵軍'), ('a', '我軍'), ('b', '共同')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='belongs_to',
            field=models.CharField(choices=[('e', '敵軍'), ('a', '我軍'), ('b', '共同')], default='b', max_length=1),
        ),
    ]
