# Generated by Django 3.2.5 on 2022-06-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vessel', '0011_missile_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='missile',
            name='cost',
            field=models.FloatField(default=0.5),
        ),
    ]
