# Generated by Django 3.2.5 on 2022-09-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vessel', '0012_missile_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='missile',
            name='range',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='vessel',
            name='weight',
            field=models.IntegerField(default=500),
        ),
    ]
