# Generated by Django 3.2.5 on 2022-04-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Battlefield', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlefield',
            name='policy',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
